export { Navbar } from './Navbar/Navbar'
export { Hero } from './Hero/Hero'
export { FeaturesSection } from './Features/Features'
export { AboutTimeLine } from './About/Timeline'
export { Footer } from './Footer/Footer'
