import './globals.css'

import { Inter } from 'next/font/google'
import LazyMotionProvider from '@/components/Providers/LazyMotionProvider'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <LazyMotionProvider>
        <body className={inter.className}>{children}</body>
      </LazyMotionProvider>
    </html>
  )
}
