name: front
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v22.6.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: yarn install
      - name: Build for production
        run: yarn build
      - name: Format the code
        run: yarn format
      - name: Lint the code
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
